--SELECT * FROM CONTAS_PAGAR
--SELECT * FROM CONTAS_RECEBER
--PROCEDURE INTEGRA CAP E CRE
--ORIGEM NOTA_FISCAL ENTRADA SAIDA
--SE SAIDA DESTINO CONTAS A RECEBER
--SE ENTRADA DESTINO CONTAS A PAGAR
--ATUALIZA NOTA FISCAL INTEGRA_FIN=S
--SEM PARAMETROS EXTERNOS, APENAS INTERNOS
--FASE 7 INTEGRACAO NFE COM FINANCEIRO CAP E CRE
--EXEC PROC_INTEGR_FIN
--DROP PROCEDURE PROC_INTEGR_FIN
CREATE PROCEDURE PROC_INTEGR_FIN (@COD_EMPRESA INT)
AS 
    SET NOCOUNT ON 
	
DECLARE @TIP_NF CHAR(1),
        @NUM_NF INT,
		@ID_CLIFOR DECIMAL(10,2),
		@COD_PAGTO INT,
		@DATA_EMISSAO DATE,
		@VENCIMENTO DATE,
		@TOTAL_NF DECIMAL(10,2),
		@VALOR_PARC DECIMAL(10,2),
		@PARC INT,
		@CONT_PARC INT,
		@ERRO_INTERNO INT
BEGIN
 BEGIN TRANSACTION
 BEGIN TRY
--ABRINDO PRIMEIRO IF VERIFICAR SE EXISTE NOTA PARA INTEGRAR
	IF (SELECT COUNT(*) FROM NOTA_FISCAL WHERE COD_EMPRESA=@COD_EMPRESA AND INTEGRADA_FIN='N')=0
	BEGIN
		SET @ERRO_INTERNO=1;
	END
	ELSE
	BEGIN
--DECLARANDO CURSOR CONTA PARCELAS
 DECLARE CONTPARC CURSOR FOR
 --LENDO TABELA QTD PARCELAS POR NF
	 SELECT A.NUM_NF,COUNT(*) CONT_PARC
	   FROM NOTA_FISCAL A
	   INNER JOIN COND_PAGTO_DET B
		 ON A.COD_PAGTO=B.COD_PAGTO
	   WHERE A.COD_EMPRESA=@COD_EMPRESA 
	   AND A.INTEGRADA_FIN='N'
	   GROUP BY A.NUM_NF
   --ABRINDO CURSOR
   OPEN CONTPARC
   --LENDO PRIMEIRO REGISTRO
   FETCH NEXT FROM CONTPARC
   --INSERINDO VALORES NA VARIAVEL
   INTO @NUM_NF,@CONT_PARC
   -- Percorrendo linhas do cursor (enquanto houverem)
   WHILE @@FETCH_STATUS = 0
	BEGIN
   --DECLARANDO CURSOR PARA INTEGRAR PARCELAS
   DECLARE INTEGRA_FIN CURSOR FOR
   --SELECIONANDO REGISTROS
   SELECT A.TIP_NF,A.NUM_NF,A.ID_CLIFOR,A.COD_PAGTO,
		  A.DATA_EMISSAO,
		  CAST(DATEADD(dd,B.DIAS,A.DATA_EMISSAO) AS DATE)VENCIMENTO,
		  A.TOTAL_NF,
		  CAST(A.TOTAL_NF/100*B.PCT AS DECIMAL(10,2)) VALOR_PARC,
		  B.PARC
   FROM NOTA_FISCAL A  
   INNER JOIN COND_PAGTO_DET B
     ON A.COD_PAGTO=B.COD_PAGTO
   WHERE COD_EMPRESA=@COD_EMPRESA 
   AND A.INTEGRADA_FIN='N'
   AND NUM_NF=@NUM_NF
   --ABRINDO CURSOR 
   OPEN INTEGRA_FIN
   --LENDO PROXIMA LINHA
   FETCH NEXT FROM INTEGRA_FIN
   --INSERINDO VALORES NA VARIAVEL
   INTO @TIP_NF,@NUM_NF,@ID_CLIFOR,@COD_PAGTO,@DATA_EMISSAO,
		@VENCIMENTO,@TOTAL_NF,@VALOR_PARC,@PARC
  -- Percorrendo linhas do cursor (enquanto NAO houverem ERROS)
  WHILE @@FETCH_STATUS = 0
	BEGIN
	--IF PARA INTEGRAR NOTAS DE VENDAS SAIDAS
	IF @TIP_NF='S'
	 BEGIN 
		INSERT INTO CONTAS_RECEBER VALUES (@COD_EMPRESA,@ID_CLIFOR,@NUM_NF,@PARC,@VENCIMENTO,NULL,@VALOR_PARC);
		SELECT  'DOCTO  VENDAS',@NUM_NF ,'INTEGRADO COM SUCESSO ','PARCELA ',@PARC,'VALOR ', @VALOR_PARC	
	 END
	--IF PARA INTEGRAR NOTAS DE COMPRAS ENTRADASS
	ELSE IF @TIP_NF='E'
	BEGIN 
		 INSERT INTO CONTAS_PAGAR VALUES (@COD_EMPRESA,@ID_CLIFOR,@NUM_NF,@PARC,@VENCIMENTO,NULL,@VALOR_PARC);
		 SELECT  'DOCTO  COMPRAS',@NUM_NF ,'INTEGRADO COM SUCESSO ','PARCELA ',@PARC,'VALOR ', @VALOR_PARC			
	END
    --IF PARA ATUALIZAR STATUS NA NF
	IF @CONT_PARC=@PARC
	BEGIN
	  --ATUALIZANDO STATUS DE NOTA FISCAL PARA INTEGRADA_FIN=S
	SELECT 'ATUALIZA '+CAST(@NUM_NF AS VARCHAR(100))
    UPDATE NOTA_FISCAL SET INTEGRADA_FIN='S' WHERE COD_EMPRESA=@COD_EMPRESA AND NUM_NF=@NUM_NF;
	END 
	--LENDO PROXIMAS LINHAS DO CURSOR
	FETCH NEXT FROM INTEGRA_FIN
    INTO @TIP_NF,@NUM_NF,@ID_CLIFOR,@COD_PAGTO,@DATA_EMISSAO,
		@VENCIMENTO,@TOTAL_NF,@VALOR_PARC,@PARC;

   END --FINAL WHILE
  
   CLOSE INTEGRA_FIN
   DEALLOCATE INTEGRA_FIN
   --LENDO PROXIMA LINHA DO CURSOR
   FETCH NEXT FROM CONTPARC
   INTO @NUM_NF,@CONT_PARC

  END --FINAL WHILE
   CLOSE CONTPARC
   DEALLOCATE CONTPARC
   
END --END DO PRIMEIRO ELSE IF
END TRY
BEGIN CATCH
	SELECT  
        ERROR_NUMBER() AS ErrorNumber,  
        ERROR_SEVERITY() AS ErrorSeverity , 
        ERROR_STATE() AS ErrorState,
        ERROR_PROCEDURE() AS ErrorProcedure , 
        ERROR_LINE() AS ErrorLine,  
        ERROR_MESSAGE() AS ErrorMessage;  

		IF (SELECT CURSOR_STATUS('global', 'INTEGRA_FIN')) = 1 
		BEGIN
			CLOSE INTEGRA_FIN	
			DEALLOCATE INTEGRA_FIN	
		END
		IF (SELECT CURSOR_STATUS('global', 'CONTPARC')) = 1 
		BEGIN
			CLOSE CONTPARC	
			DEALLOCATE CONTPARC	
		END	
		
		SET XACT_ABORT ON;
		IF @@TRANCOUNT > 0  
        ROLLBACK TRANSACTION; 
END CATCH

--VERIFICACOES FINAIS
   IF @@ERROR <> 0 
		BEGIN
		  ROLLBACK TRANSACTION
		  PRINT @@error
		  PRINT 'OPERACAO CANCELADA' 
		END
	ELSE IF @ERRO_INTERNO=1
	BEGIN 
	    ROLLBACK TRANSACTION 
		PRINT 'NAO A DOCUMENTOS PARA SEREM PROCESSADOS'
	END
	ELSE
		BEGIN
			COMMIT TRANSACTION
		     PRINT 'INTEGRACAO CONCLUIDA'
		END 
END
--FIM PROCEDURES

EXECUTE PROC_INTEGR_FIN 1


